apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nks-sf-pdl
  namespace: teamnks
  labels:
    team: teamnks
spec:
  webproxy: true
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 9Gi
    requests:
      cpu: 100m
      memory: 8Gi
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais-q.adeo.no
  envFrom:
    - secret: nks-sf-pdl-secret
  filesFrom:
    - secret: nks-sf-pdl-secret
  kafka:
    pool: nav-dev # enum of nav-dev, nav-prod
  env:
    - name: KAFKA_BROKERS_ON_PREM # Conflict with automatic env variable set by gcp kafka pool makes need for separate config to on-prem kafka_brokers
      value: SASL_SSL://b27apvl00045.preprod.local:8443,SASL_SSL://b27apvl00046.preprod.local:8443,SASL_SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_SCREG
      value: https://kafka-schema-registry.nais-q.adeo.no
    - name: KAFKA_CLIENTID
      value: nks-sf-pdl-sit
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC
      value: privat-person-pdl-dokument-tagged-v1
    - name: KAFKA_TOPIC_GT
      value: aapen-pdl-geografisktilknytning-v1
    - name: KAFKA_PRODUCER_TOPIC
      value: teamnks.nks-sf-pdl-v2
    - name: KAFKA_PRODUCER_TOPIC_GT
      value: teamnks.nks-sf-gt-v1
    - name: KAFKA_USER
      value: srvsfpdl
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: VAULT_INSTANCE
      value: GCP